apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-management-core
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saurabhd2106/argocd-gitops.git
    targetRevision: main
    path: apps/user-management
  destination:
    server: https://kubernetes.default.svc
    namespace: user-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true